export const slidesData = [
  {
    id: 1,
    img: "https://images.unsplash.com/photo-1513326738677-b964603b136d",
    title: "Moscow",
    description: "The capital of modern Russia.",
    flag: "RU",
    soundtrack: "Rasputin - Boney M",
    movie: "Gentleman in Moscow - 2024",
  },
  {
    id: 2,
    img: "https://images.unsplash.com/photo-1552832230-c0197dd311b5",
    title: "Rome",
    description:
      "Posesses the largest ancient amphitheatre ever built in Rome.",
    flag: "IT",
    soundtrack: "Mambo Italiano",
    movie: "Godfather - Francis Ford Coppola - 1972",
  },
  {
    id: 3,
    img: "https://images.unsplash.com/photo-1535189043414-47a3c49a0bed",
    title: "Seoul",
    description: "A high-tech city where palaces meet skyscrapers.",
    flag: "KR",
    soundtrack: "Gangnam Style",
    movie: "Parasite - 2019 - Bong Joon Ho",
  },
  {
    id: 4,
    img: "https://images.unsplash.com/photo-1549693578-d683be217e58",
    title: "Tokyo",
    description: "The neon-lit heart of Japan's megalopolis.",
    flag: "JP",
    soundtrack: "Big in Japan",
    movie: "Lost in Translation - 2003 - Sofia Coppola",
  },
  {
    id: 5,
    img: "https://images.unsplash.com/photo-1508009603885-50cf7c579365",
    title: "Bangkok",
    description: "The vibrant, bustling gateway to Southeast Asia.",
    flag: "TH",
    soundtrack: "One Night in Bangkok",
    movie: "The Hangover Part II - 2011 - Todd Phillips",
  },
  {
    id: 6,
    img: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34",
    title: "Paris",
    description: "The City of Light and the capital of art and romance.",
    flag: "FR",
    soundtrack: "La Vie En Rose",
    movie: "Amelie",
  },
  {
    id: 7,
    img: "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9",
    title: "New York",
    description: "The city that never sleeps, featuring Times Square.",
    flag: "US",
    soundtrack: "Empire State of Mind",
    movie: "Home Alone",
  },
  {
    id: 8,
    img: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c",
    title: "Dubai",
    description: "Home to the Burj Khalifa and world-class luxury.",
    flag: "AE",
    soundtrack: "Nour El Ein by Amir Diab",
  },
  {
    id: 9,
    img: "https://images.unsplash.com/photo-1518639192441-8fce0a366e2e?q=80&w=1171&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    title: "Rio de Janeiro",
    description: "Famous for its carnival and the Christ the Redeemer statue.",
    flag: "BR",
    soundtrack: "The Girl from Ipanema",
    movie: "Rio - 2011 - Disney",
  },
  {
    id: 10,
    img: "https://images.unsplash.com/photo-1520986606214-8b456906c813?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    title: "London",
    description: "The historic capital of England on the River Thames.",
    flag: "GB",
    soundtrack: "London Calling",
    movie: "Singing in the Rain",
  },
  {
    id: 11,
    img: "https://images.unsplash.com/photo-1565967511849-76a60a516170?q=80&w=1171&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    title: "Singapore",
    description:
      "A futuristic garden city where nature and high-tech architecture coexist.",
    flag: "SG",
    soundtrack: "Singapore by OneRepublic",
  },
  {
    id: 12,
    img: "https://images.unsplash.com/photo-1577871598838-a543ee47cd79?q=80&w=1166&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    title: "Hong Kong",
    description:
      "The energetic pulse of Asia—a high-density metropolis famous for its skyline, street food, and deep-water port.",
    flag: "HK",
    soundtrack: "Hungry Like the Wolf by Duran Duran",
    movie: "Jackie Chan",
  },
  {
    id: 13,
    img: "https://images.unsplash.com/photo-1585208798174-6cedd86e019a?q=80&w=1173&auto=format&fit=crop",
    title: "Lisbon",
    description:
      "A hilly, coastal capital known for its yellow trams and Fado music.",
    flag: "PT",
    soundtrack: "Canção do Mar by Dulce Pontes",
  },
  {
    id: 14,
    img: "https://images.unsplash.com/photo-1604631832503-a0bc87125967?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    title: "Kuala Lumpur",
    description:
      "Home to the iconic Petronas Twin Towers and a melting pot of cultures.",
    flag: "MY",
    soundtrack: "Sejahtera Malaysia",
  },
  {
    id: 15,
    img: "https://images.unsplash.com/photo-1578912996078-305d92249aa6?q=80&w=1171&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    title: "Barcelona",
    description:
      "Art, architecture, and Mediterranean vibes in the heart of Catalonia.",
    flag: "ES",
    soundtrack: "Barcelona by Freddie Mercury & Montserrat Caballé",
  },
  {
    id: 16,
    img: "https://images.unsplash.com/photo-1512470876302-972faa2aa9a4?q=80&w=1170&auto=format&fit=crop",
    title: "Amsterdam",
    description: "Famous for its intricate canal system and artistic heritage.",
    flag: "NL",
    soundtrack: "Amsterdam by Coldplay",
    movie: "Diamonds are forever - Guy Hamilton - 1971",
  },
  {
    id: 17,
    img: "https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?q=80&w=1170&auto=format&fit=crop",
    title: "Sydney",
    description:
      "The stunning harbor city featuring the Opera House and Bondi Beach.",
    flag: "AU",
    soundtrack: "Down Under by Men at Work",
    movie: "Anyone but you - 2023",
  },
  {
    id: 18,
    img: "https://images.unsplash.com/photo-1523906834658-6e24ef2386f9?q=80&w=1166&auto=format&fit=crop",
    title: "Venice",
    description: "A magical city of canals, gondolas, and Renaissance palaces.",
    flag: "IT",
    soundtrack: "O Sole Mio",
    movie: "Don't Look Now (1973)",
  },
  {
    id: 19,
    img: "https://images.unsplash.com/photo-1531572753322-ad063cecc140?q=80&w=1176&auto=format&fit=crop",
    title: "Athens",
    description:
      "The birthplace of democracy and home to the ancient Acropolis.",
    flag: "GR",
    soundtrack: "Zorba the Greek",
    movie: "Dogtooth (2009)",
  },
  {
    id: 20,
    img: "https://images.unsplash.com/photo-1553913861-c0fddf2619ee?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    title: "Cairo",
    description: "A sprawling desert metropolis guarded by the Great Pyramids.",
    flag: "EG",
    soundtrack: "Enta Omri by Umm Kulthum",
    movie: "The Spy Who Loved Me (1977)",
  },
];
